settings:
  legacy:
    force: false
    interval: 100ms
server:
  status: false
  open: false
  host: localhost
  port: 8090
schema:
  - name: server
    path: .
    commands:
      install:
        status: true
        method: go install -v ./...
      run:
        status: true
        method: watchme
    watcher:
      paths:
        - /
      extensions:
        - go
        - html
      ignored_paths:
        - vendor
        - node_modules
      scripts:
        - type: before
          command: go get -d -v ./...
          output: true
