version: "3.7"

services:

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    networks:
      - watchme_network
    volumes:
      - .:/go/src/github.com/ugniusin/watchme-backend
    links:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: always
    environment:
      MYSQL_DATABASE: watchme
      MYSQL_USER: root
      MYSQL_PASSWORD: toor
      MYSQL_ROOT_PASSWORD: toor
    networks:
      - watchme_network
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  watchme_network: